#pragma once

#include <QMainWindow>

#include <future>
#include <memory>

#include <jsoncpp/json/json.h>

#include "GameTypes.hpp"
#include "MessageQueue.hpp"

namespace Ui {
class RangeUI;
}

/// A simple starting point for a motion detection test program
class RangeUI final : public QMainWindow {
	Q_OBJECT

public:

	explicit RangeUI(QWidget *parent = 0);

	~RangeUI();

private:

	void connectToSM();

	bool ensureConnection();

	void closeConnection();

	std::unique_ptr<Message> awaitResponse(Message* toSend);

	void setup();

	void start();

	void stop();

	void getStatus();

	void getResults();

	Ui::RangeUI *ui; ///< The window, generated by Qt's UI file

	Json::StyledWriter jWriter;

	message_id_t uid = 0;

	std::future<void> commsThread;

	MessageQueue toSM;
	MessageQueue fromSM;
};
