#pragma once

#include <QMainWindow>

#include <thread>
#include <memory>

#include <jsoncpp/json/json.h>

#include "GameTypes.hpp"
#include "MessageQueue.hpp"

namespace Ui {
class RangeUI;
}

/// A simple starting point for a motion detection test program
class RangeUI final : public QMainWindow {
	Q_OBJECT

public:

	explicit RangeUI(QWidget *parent = 0);

	~RangeUI();


private:

	void connectToSM();

	void closeConnection();

	void getStatus();

	Ui::RangeUI *ui; ///< The window, generated by Qt's UI file

	Json::StyledWriter jWriter;

	message_id_t uid = 0;

	std::unique_ptr<std::thread> commsThread;

	MessageQueue toSM;
	MessageQueue fromSM;
};
