#pragma once

#include <QMainWindow>

namespace Ui {
class RangeUI;
}

/// A simple starting point for a motion detection test program
class RangeUI final : public QMainWindow {
	Q_OBJECT

public:

	explicit RangeUI(QWidget *parent = 0);

	~RangeUI();

private:

	Ui::RangeUI *ui; ///< The window, generated by Qt's UI file

	// TODO: Fill

private slots:

	// TODO: Fill
};
